import { SpendingCategory } from 'Types/SpendingCategory';
import { ReactElement } from 'react';
import {
    FaCannabis,
    FaCar,
    FaChargingStation,
    FaCookieBite,
    FaDollarSign,
    FaGasPump,
    FaGift,
    FaHome,
    FaMoneyBillAlt,
    FaSmoking,
    FaTshirt,
} from 'react-icons/fa';
import {
    MdBrush,
    MdBusinessCenter,
    MdContentCut,
    MdFastfood,
    MdFitnessCenter,
    MdHealing,
    MdHotel,
    MdLocalAirport,
    MdLocalGroceryStore,
    MdMovieFilter,
    MdPets,
    MdSchool,
    MdShield,
    MdShoppingBag,
    MdSportsBar,
    MdTrain,
    MdVideogameAsset,
    MdWaterDrop,
} from 'react-icons/md';

const spendCategoryIconMapper: Record<SpendingCategory, ReactElement> = {
    AIRFARE: <MdLocalAirport />,
    BUSINESS: <MdBusinessCenter />,
    CANNABIS: <FaCannabis />,
    CLOTHING: <FaTshirt />,
    DRINKS: <MdSportsBar />,
    EDUCATION: <MdSchool />,
    ENTERTAINMENT: <MdMovieFilter />,
    EV_CHARGING: <FaChargingStation />,
    FITNESS: <MdFitnessCenter />,
    FUEL: <FaGasPump />,
    GAMES: <MdVideogameAsset />,
    GIFTS: <FaGift />,
    GROOMING: <MdContentCut />,
    GROCERIES: <MdLocalGroceryStore />,
    HEALTH: <MdHealing />,
    HOBBY: <MdBrush />,
    HOUSING: <FaHome />,
    INSURANCE: <MdShield />,
    LODGING: <MdHotel />,
    MATERIAL_ITEMS: <MdShoppingBag />,
    NICOTINE: <FaSmoking />,
    OTHER: <FaDollarSign />,
    PETS: <MdPets />,
    RESTAURANTS: <MdFastfood />,
    TAXES: <FaMoneyBillAlt />,
    TRANSPORTATION: <MdTrain />,
    TREATS: <FaCookieBite />,
    UTILITIES: <MdWaterDrop />,
    VEHICLE: <FaCar />,
} as const;

export default spendCategoryIconMapper;
