const locale = {
    dashboard: {
        monthOverview: '{{0}} overview',
        totalSpent: 'Total spent',
        discretionaryTotal: 'Discretionary total',
        recurringTotal: 'Recurring total',
        spendRatio: 'Discretionary ratio',
        topCategories: 'Top discretionary categories',
    },
    spendingData: {
        topFour: 'Top four cat. total',
        other: 'Rest of spending',
        moreLabel: 'See more',
    },
    general: {
        empty: '--',
        submit: 'Submit',
        cancel: 'Cancel',
        delete: 'Delete',
    },
    transactions: {
        recent: 'Recent transactions',
        todayLabel: '{{0}} - Today',
        yesterdayLabel: '{{0}} - Yesterday',
        emptyPlaceholder: '--',
        clearSelection: 'Clear selection',
        logExpense: 'Log expense',
        newExpense: 'New expense',
        editExpense: 'Edit expense',
        deleteExpense: 'Permanently delete this expense',
        amountLabel: 'Amount',
        categoryLabel: 'Category',
        notesLabel: 'Notes',
        dateLabel: 'Date of Expense',
        tripLabel: 'Linked Trip',
        notesPlaceholder: 'About your expense',
        amountPlaceholder: '$0.00',
    },
    recurringSpending: {
        pageTitle: 'Recurring spending',
        createNew: 'Create recurring expense',
        monthlyTransactions: 'Monthly transactions',
        inactiveTransactions: 'Inactive transactions',
        estimatedMonthlyTotal: 'Estimated monthly total',
        monthActualTotal: `{{0}} actual total`,
        estimatedLabel: 'Estimated: {{0}}',
        fixedLabel: 'Fixed',
        newRecurringExpenseTitle: 'New recurring expense',
        recurringSpendName: 'Expense name',
        newSpendNamePlaceholder: 'Rent payment',
        categoryLabel: 'Category',
        variableExpenseLabel: 'This amount varies',
        variableExpenseDescription: 'The amount of this expense varies from month to month, like a utility bill.',
        monthlyAmountLabel: 'Monthly amount',
        monthlyAmountVariesLabel: 'Estimated monthly amount',
        monthlyAmountPlaceholder: '$0.00',
        deleteSpeedBumpHeader: 'Are you sure?',
        deleteSpeedBumpDescription:
            'This will permanently delete this recurring expense and all of its past data. This means all previous months\' spend data for "{{0}}" will be permanently deleted.',
        finalDeletionWarning: 'This action cannot be undone.',
        edit: 'Edit',
        permanentlyDelete: 'Permanently delete',
        cancel: 'Cancel',
        chooseOption: 'What would you like to do?',
        editingTransaction: 'Edit "{{0}}"',
        deletingTransaction: 'Delete "{{0}}"',
    },
    ACCOUNT_CATEGORIES: {
        CHECKING: 'Checking',
        SAVINGS: 'Savings',
        INVESTING: 'Investment',
        BONDS: 'Bonds',
    },
    SPENDING_CATEGORIES: {
        RESTAURANTS: 'Dining out',
        DRINKS: 'Drinks',
        GROCERIES: 'Groceries',
        ENTERTAINMENT: 'Entertainment',
        EV_CHARGING: 'EV charging',
        TRANSPORTATION: 'Transportation',
        VEHICLE: 'Vehicle',
        FUEL: 'Fuel',
        FITNESS: 'Fitness',
        GROOMING: 'Grooming & self-care',
        BUSINESS: 'Business expense',
        MATERIAL_ITEMS: 'Material items',
        AIRFARE: 'Airfare',
        LODGING: 'Lodging',
        HEALTH: 'Healthcare',
        CLOTHING: 'Clothing',
        GIFTS: 'Gifts & charity',
        EDUCATION: 'Education',
        UTILITIES: 'Utilities',
        HOUSING: 'Housing',
        CANNABIS: 'Cannabis',
        PETS: 'Pets',
        INSURANCE: 'Insurance',
        NICOTINE: 'Nicotine',
        GAMES: 'Games',
        HOBBY: 'Hobbies',
        TREATS: 'Treats',
        TAXES: 'Taxes',
        OTHER: 'Other',
    },
} as const;

export default locale;
